language: node_js
node_js:
- '0.11'
before_install:
- npm config set loglevel warn
script:
- node --harmony transformer/transform
after_success:
- git config --global user.email "hincubus@gmail.com"
- git config --global user.name "Hinc Liu"
- git remote set-url origin https://github.com/scrat-team/font-awesome.git
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git checkout master
- git add .
- git commit -am "[ci skip]"
- git push origin master
branches:
  only:
  - master
env:
  global:
  - secure: ZP+3wqojRUzoNpPbA3RxkfqdM5LNVKbgr3iAn3ScbGOow8dOZ2Pv3Hkf2qc6iZeOE2p/ETapRwbi1BL0XneqYN082cKaicBitHf6SiZH9hueW1Y7KXm6JQDlV+GB8i+Cs1VnBZnZpBw0GZAn6O3WEYJ+UxBYkERBmzB+eVYWXFg=
